# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(db_index=True)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('t_type', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
